import 'package:get/get.dart';

class WorldLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'mon': "mon",
          'tue': "tue",
          'wed': "wed",
          'thu': "thu",
          'fri': "fri",
          'sat': "sat",
          'sun': "sun",
          'january': "January",
          'february': "February",
          'march': "March",
          'april': "April",
          'may': "May",
          'june': "June",
          'july': "July",
          'august': "August",
          'september': "September",
          'october': "October",
          'november': "November",
          'december': "December",
          "select_language": "Select language",
          "save": "Save",
          "bracelet_disconnected": "BRACELET\nDISCONNECTED",
          "sign_in": "Sign-In",
          "sign_up": "Sign-Up",
          "email": "Email",
          "password": "Password",
          "confirm_password": "Confirm Password",
          "forgot_password": "Forgot Password",
          "first_name": "First Name",
          "last_name": "Last Name",
          "phone": "Phone",
          "enter_your_first_name": "Enter Your First Name",
          "enter_your_last_name": "Enter Your Last Name",
          "enter_email_address": "Enter Email Address",
          "enter_phone_number": "Enter Phone Number",
          "enter_password": "Enter Password",
          "confirm_password_does_not_matched":
              "Confirm password does not matched",
          "password_should_be": "Password should be",
          "did_not_receive_the_code": "Did not receive the code",
          "you_can_change_language": "You can change language",
          "resend_code_successful": "Resend code successful",
          "country_of_residence": "Country of Residence",
          "enter_new_password": "Enter new password.",
          "confirm_your_password": "Confirm your password",
          "new_password": "New password",
          "reset_password": "Reset password",
          "re_order": "Re order",
          "privacy_policy": "Privacy Policy",
          "logout": "Logout",
          "are_you_sure_to_logout": "Are you sure to logout ?",
          "yes": "Yes",
          "no": "No",
          "home": "Home",
          "setting": "Setting",
          "change_password": "Change password",
          "today": "Today",
          "not_connect_to_its_paired_phone_this_usually_means_your_phone_is_not_within_bluetooth":
              "Your Bracelet can not connect\n to its paired phone.\nThis usually means your phone \nis not within Bluetooth.",
          "tomorrow": "Tomorrow",
          "name": "Name",
          "Connection": "Connection",
          "connect_with_bluetooth": "Connect with Bluetooth",
          "bracelet_connected": "BRACELET\nCONNECTED\n",
          "year": "Year",
          "month": "Month",
          "week": "Week",
          "day": "Day",
          "hour": "Hour",
          "subscribe_to_our_new_channel_to_get_latest_updates":
              "Subscribe to our new channel to get latest updates",
          "your_email_address": "Your email address",
          "logo": "Logo",
          "minute": "Minute",
          "hours": "Hours",
          "login": "Login",
          "continue_with_google": "Continue with google",
          "i_forgot_my_password": "I forgot my password",
          "dont_have_an_account": "Don't have an account ?",
          "create_an_account": "Create an account",
          "device_name": "Device name",
          "your_bracelet_is_connected_successfully":
              "Your bracelet is connected successfully",
          "connected": "Connected",
          "go_home": "Go Home",
          "connection_problem": "CONNECTION PROBLEM",
          "turn_off_Bluetooth_for_15_seconds_or_force_the_app_to_close_and_relaunch_it.":
              "Turn off Bluetooth for 15 seconds or \n force the app to_close_and_relaunch_it.",
          "please_wear_your_bracelet_and_reconnect_it":
              "Please wear your bracelet and reconnect it.",
          "unworn_bracelet": "Unworn\nBracelet",
          "open_your_mailbox_and_click_on_the_reset_password_link_in_the_message_you_received":
              "Open your mailbox and click on the reset password link_in the message you received.",
          "send": "Send",
          "done": "Done",
          "welcome": "Welcome\n",
          "lets_get_started_with_creating_your_knowlepsy_account":
              "Lets get started with creating \nyour knowlepsy account",
          "please_enter_the_information_of_the_person_that_will_use_knowlepsy_bracelet":
              "Please enter the information \n of the person that will use knowlepsy bracelet.",
          "enter_your_email_address": "Enter your email address",
          "choose_a_password": "Choose a password",
          "birthday_date ": "Birthday date",
          "create_my_account": "Create my account",
          "open_mailbox": "Open mailbox",
          "open_your_mailbox_and_click_on_the_activation_link_in_the_message_you_received":
              "Open your mailbox and click on_the_activation_link_in_the_message_you_received",
          "confirmation": "Confirmation",
          "approved_seizure": "APPROVED SEIZURE",
          "seizure": "Seizure ",
          "log_an_undetected_seizure_alert": "Log an undetected seizure alert",
          "hi": "Hi,",
          "undetected_seizure": "UNDETECTED SEIZURE",
          "false_alarm": "FALSE ALARM",
          "schedule": "Schedule",
          "time": "Time",
          "add_a_comment": "Add a comment",
          "the_circumstance_of_the_seizure":
              "The Circumstance \nof the seizure",
          "seizure_alert": "Seizure alert",
          "at": "at",
          "if_yo_dont_cancel_the_alert_the_following_caregivers_will_be_notified":
              "If you dont cancel the alert the following caregivers will be notified",
          "secondes": "secondes",
          "true_alert": "True Alert",
          "insert_a_medecine": "Insert a medecine",
          "medecine": "Medecine ",
          "insert_name_of_medicine": "Insert name of medicine",
          "dosage": "Dosage",
          "quantity": "Quantity",
          "remind_me": "Remind me",
          "mg": "mg",
          "ml": "ml",
          "personal_information": "Personal Information",
          "access_and_control": "Access and control",
          "name_of_the_device": "Name of the device",
          "language": "Language",
          "family_name": "Family name",
          "confirme": "Confirmer",
          "take_photo": "Take_photo",
          "take_a_new_photo_or_import_one_from_your_library":
              "Take a new photo or import one from your library",
          "gallery": "Gallery",
          "camera": "Camera",
          "your_old_password": "Your old password",
          "change": "Change",
          "activated": "Activated",
          "add_caregiver": "Add caregiver",
          "add": "Add",
          "not_confirmed": "not confirmed",
          "your_caregiver_will_receive_an_email_to_download_the_application_and_confirm_the_invitation_as_a_caregiver":
              "Your caregiver will receive an email to download the application and confirm the invitation as a caregiver.",
          "open_my_mailbox": "Open my mailbox",
          "english": "English",
          "french": "French",
          "if_you_dont_cancel_the_alert_the_following_caregivers_will_be_notified.":
              "if you dont cancel the alert the following caregivers will be notified.",
          "injection_reminder": "Injection reminder",
          "tegretol": "Tegretol",
          "reminder_for_pill": "Reminder for pill",
          "click_to_connect": "Click to connect",
          "taken": "Taken",
          "pending": "Pending",
          "insert_medecine": "Insert Medecine",
          "insert_name_of_medecine": "Insert name of medecine",
          'One': "One",
          'Two': "Two",
          'Three': "Three",
          'Four': "Four",
          "se": "Se",
          "active": "Active",
          "notactive": "Not active",
        },

        'fr_FR': {
          'mon': "Lun",
          'tue': "Mar",
          'wed': "Mer",
          'thu': "Jeu",
          'fri': "Ven",
          'sat': "Sam",
          'sun': "Dim",
          'january': "Janvier",
          'february': "Février",
          'march': "Mars",
          'april': "Avril",
          'may': "Mai",
          'june': "Juin",
          'july': "Juillet",
          'august': "Août",
          'september': "Septembre",
          'october': "Octobre",
          'november': "Novembre ",
          'december': "Décembre",
          "click_to_connect": "Cliquez pour vous connecter",
          "select_language": "Sélectionner la langue",
          "save": "Enregistrer",
          "bracelet_disconnected": "BRACELET\nDÉBRANCHÉ",
          "sign_in": "Connexion",
          "sign_up": "S'inscrire",
          "email": "E-mail",
          "password": "Mot de passe",
          "confirm_password": "Confirmer le mot de passe",
          "forgot_password": "Mot de passe oublié",
          "first_name": "Prénom",
          "last_name": "Nom de famille",
          "phone": "Téléphone",
          "enter_your_first_name": "Saisir votre prénom",
          "enter_your_last_name": "Saisir votre nom de famille",
          "enter_email_address": "Saisir votre adresse e-mail",
          "enter_phone_number": "Saisir votre numéro de téléphone",
          "enter_password": "Saisir votre mot de passe",
          "confirm_password_does_not_matched":
              "Le mot de passe confirmé ne correspond pas",
          "password_should_be":
              "Le mot de passe saisi doit comporter plus de 6 caractères",
          "did_not_receive_the_code": "Vous n'avez pas reçu le code ?",
          "you_can_change_language":
              "*Vous pouvez changer de langue plus tard depuis la barre de menu",
          "resend_code_successful": "code renvoyé avec succès",
          "country_of_residence": "Pays de résidence",
          "enter_new_password":
              "Veuillez saisir et confirmer votre nouveau mot de passe.",
          "confirm_your_password": "Confirmer votre mot de passe",
          "new_password": "Nouveau mot de passe",
          "reset_password": "Réinitialiser le mot de passe",
          "re_order": "replacer la commande",
          "privacy_policy": "Politique de confidentialité",
          "logout": "Déconnexion",
          "are_you_sure_to_logout": "Voulez-vous vraiment vous déconnecter ?",
          "yes": "oui",
          "no": "non",
          "home": "Accueil",
          "setting": "Paramètre",
          "change_password": "Modifier le mot de passe",
          "today": "Aujourd'hui",
          "your_bracelet_can_not_connect_to_its_paired_phone_this_usually_means_your_phone_is_not_within_bluetooth":
              "Votre bracelet ne peut pas se connecter\n à son téléphone jumelé. \nCela signifie généralement que votre téléphone \n n'est pas en Bluetooth.",
          "tomorrow": "Demain",
          "name": "nom",
          "Connection": "connexion",
          "connect_with_bluetooth": "Connectez-vous avec Bluetooth",
          "bracelet_connected": "BRACELET\nCONNECTED",
          "year": "année",
          "month": "mois",
          "week": "semaine",
          "day": "jour",
          "hour": "heure",
          "subscribe_to_our_new_channel_to_get_latest_updates":
              "Abonnez-vous à notre newsletter pour recevoir les dernières mises à jour",
          "your_email_address": "Votre adresse e-mail",
          "logo": "Logo",
          "minute": "Minute",
          "hours": "Heures",
          "login": "Connexion",
          "continue_with_google": "Continuer avec Google",
          "i_forgot_my_password": "J’ai oublié mon mot de passe",
          "dont_have_an_account": "Vous n’avez pas de compte ? ",
          "create_an_account": "Créer un compte",
          "device_name": "Nom de l’appareil",
          "your_bracelet_is_connected_successfully":
              "Votre bracelet est connecté avec succès",
          "connected": "connecté",
          "go_home": "Accueil",
          "connection_problem": "PROBLÈME\nDE CONNEXION",
          "turn_off_Bluetooth_for_15_seconds_or_force_the_app_to_close_and_relaunch_it.":
              "Désactivez le Bluetooth pendant 15 secondes ou \n forcez l'application à se fermer et à la relancer.",
          "please_wear_your_bracelet_and_reconnect_it":
              "Veuillez porter votre bracelet et le reconnecter.",
          "unworn_bracelet": "Bracelet\nnon \nporté",
          "open_your_mailbox_and_click_on_the_reset_password_link_in_the_message_you_received":
              "Ouvrez votre boîte aux lettres et cliquez sur le lien de réinitialisation du mot de passe dans le message que vous avez reçu.",
          "send": "Envoyer",
          "done": "Fait",
          "welcome": "Bienvenue",
          "lets_get_started_with_creating_your_knowlepsy_account":
              "Commençons par créer votre compte knowlepsy!",
          "please_enter_the_information_of_the_person_that_will_use_knowlepsy_bracelet":
              "Veuillez entrer les informations de la personne qui utilisera le bracelet knowlepsy.",
          "enter_your_email_address": "Entrez votre adresse courriel",
          "choose_a_password": "Choisir un mot de passe",
          "birthday_date ": "Date de naissance",
          "create_my_account": "Créer mon compte",
          "open_mailbox": "Ouvrir boîte email ",
          "open_your_mailbox_and_click_on_the_activation_link_in_the_message_you_received":
              "Ouvrez votre boîte aux lettres et cliquez sur le lien d’activation dans le message vous avez reçu",
          "confirmation": "Fait",
          "approved_seizure": "Crise confirmé",
          "seizure": "crise ",
          "log_an_undetected_seizure_alert":
              "Consigner une alerte de crise non détectée",
          "hi": "Bonjour,",
          "undetected_seizure": "Crise non détectée",
          "false_alarm": "fausse alerte",
          "schedule": "Calendrier",
          "time": "Temps",
          "add_a_comment": "Ajouter un commentaire",
          "the_circumstance_of_the_seizure": "Les circonstances de la Crise",
          "seizure_alert": "Alerte Crise",
          "at": "à",
          "if_yo_dont_cancel_the_alert_the_following_caregivers_will_be_notified":
              "si vous ne pouvez pas annuler l’alerte, les soignants suivants seront avisés",
          "secondes": "secondes",
          "true_alert": "True Alert",
          "insert_a_medecine": "Insérer un médicament",
          "medecine": "Médecine ",
          "insert_name_of_medicine": "Insérer le nom du médicament",
          "dosage": "Dosage",
          "quantity": "Quantité",
          "remind_me": "Rappelle moi",
          "mg": "mg",
          "ml": "ml",
          "personal_information": "Informations personnelles",
          "access_and_control": "Accès et contrôle",
          "Name_of_the_device": "Nom de l'appareil",
          "language": "Langue",
          "family_name": "Nom de famille",
          "confirme": "Confirmer",
          "take_photo": "Prendre une photo",
          "take_a_new_photo_or_import_one_from_your_library":
              "Prendre une nouvelle photo ou en importer une de votre bibliothèque",
          "gallery": "Galerie",
          "camera": "Caméra",
          "your_old_password": "Votre ancien mot de passe",
          "change": "Changer",
          "activated": "activé",
          "add_caregiver": "Ajouter un aidant",
          "add": "Ajouter",
          "not_confirmed": "Non confirmé",
          "your_caregiver_will_receive_an_email_to_download_the_application_and_confirm_the_invitation_as_a_caregiver":
              "Votre aidant de soins recevra un courriel pour télécharger la demande et confirmer l’invitation à titre de fournisseur de soins.",
          "open_my_mailbox": "Ouvrir ma boîte aux lettres",
          "english": "Anglais",
          "french": "Français",
          "if_you_dont_cancel_the_alert_the_following_caregivers_will_be_notified.":
              "Si vous n’annulez pas l’alerte, ce qui suit Les soignants seront avisés.",
          "injection_reminder": "Rappel d’injection",
          "tegretol": "Tegretol",
          "reminder_for_pill": "Rappel de pilule",
          "taken": "pris",
          "pending": "En attente",
          "insert_medecine": "Insérer un médicament",
          "insert_name_of_medecine": "Insérer le nom de la médecine",
          'One': "Un",
          'Two': "Deux",
          'Threes': "Trois",
          'Four': "Quatre",
          "se": "voir",
          "active": "Actif",
          "notactive": "Non actif",
        },

        //add more language here
      };
}
